#! /bin/bash
rm /var/www/html/index.nginx-debian.html
service postgresql start
service php8.1-fpm start
service nginx start

adduser postgres
adduser --quiet --disabled-password --shell /bin/bash --home /home/www --gecos "www" www
echo "www:www" | chpasswd

su - postgres <<EOF
psql -U postgres -c "create database www;" 
psql -U postgres -c "create user www with encrypted password 'www';"
psql -U postgres -c "grant ALL ON DATABASE www to www;"
EOF
su - www <<EOF
psql -U www --dbname=www < /var/www/html/asd.sql
EOF